// const diaHoy = new Date('7-20-1997');
const diaHoy = new Date();
let valor;
valor = diaHoy;
valor = diaHoy.getFullYear();
valor = diaHoy.getMonth();
valor = diaHoy.getHours();
valor = diaHoy.getTime();
valor = diaHoy.setFullYear(2010);
console.log(valor);